# Generated by Django 4.2.29 on 2026-04-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=500, unique=True)),
                ('class_days', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=5)),
                ('batch_start_date', models.DateField()),
                ('batch_end_date', models.DateField()),
                ('instructor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('instructor_email', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('enrolled_type', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_code', on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='core.batch')),
            ],
            options={
                'db_table': 'learners',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_email', models.CharField(max_length=300)),
                ('class_date', models.DateField()),
                ('status', models.CharField(default='queued', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_code', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.batch')),
            ],
            options={
                'db_table': 'email_logs',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_code', on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='core.batch')),
            ],
            options={
                'db_table': 'cancellations',
            },
        ),
        migrations.CreateModel(
            name='Postponement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('new_date', models.DateField()),
                ('new_time', models.CharField(max_length=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_code', on_delete=django.db.models.deletion.CASCADE, related_name='postponements', to='core.batch')),
            ],
            options={
                'db_table': 'postponements',
                'indexes': [models.Index(fields=['batch', 'original_date'], name='ix_postponements_batch_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='postponement',
            constraint=models.UniqueConstraint(fields=('batch', 'original_date'), name='uq_postponement_batch_date'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('email', 'batch'), name='uq_learner_email_batch'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['batch', 'class_date', 'learner_email'], name='ix_email_logs_batch_date_email'),
        ),
        migrations.AddIndex(
            model_name='cancellation',
            index=models.Index(fields=['batch', 'cancelled_date'], name='ix_cancellations_batch_date'),
        ),
        migrations.AddConstraint(
            model_name='cancellation',
            constraint=models.UniqueConstraint(fields=('batch', 'cancelled_date'), name='uq_cancellation_batch_date'),
        ),
    ]
